
version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: beedab
      POSTGRES_PASSWORD: beedab
      POSTGRES_DB: beedab_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beedab"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
