declare function createTestAdmin(): Promise<{
    id: number;
    username: string;
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    phone: string | null;
    userType: string;
    role: string;
    permissions: string[] | null;
    avatar: string | null;
    bio: string | null;
    isVerified: boolean | null;
    isActive: boolean | null;
    reacNumber: string | null;
    lastLoginAt: Date | null;
    createdAt: Date | null;
    updatedAt: Date | null;
}>;
declare function createTestData(): Promise<void>;
declare function testAdminEndpoints(): Promise<void>;
export { createTestAdmin, createTestData, testAdminEndpoints };
