
-- Initial schema migration
-- Users table
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  phone TEXT,
  user_type TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  permissions TEXT,
  avatar TEXT,
  bio TEXT,
  is_verified BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  reac_number TEXT,
  last_login_at BIGINT,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);

-- Properties table
CREATE TABLE IF NOT EXISTS properties (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  price TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  zip_code TEXT NOT NULL,
  latitude TEXT,
  longitude TEXT,
  property_type TEXT NOT NULL,
  listing_type TEXT NOT NULL,
  bedrooms INTEGER,
  bathrooms TEXT,
  square_feet INTEGER,
  area_build INTEGER,
  lot_size TEXT,
  year_built INTEGER,
  status TEXT NOT NULL DEFAULT 'active',
  images TEXT,
  features TEXT,
  virtual_tour_url TEXT,
  video_url TEXT,
  property_taxes TEXT,
  hoa_fees TEXT,
  owner_id INTEGER REFERENCES users(id),
  agent_id INTEGER REFERENCES users(id),
  views INTEGER DEFAULT 0,
  days_on_market INTEGER DEFAULT 0,
  auction_date BIGINT,
  auction_time TEXT,
  starting_bid TEXT,
  current_bid TEXT,
  reserve_price TEXT,
  auction_house TEXT,
  auctioneer_name TEXT,
  auctioneer_contact TEXT,
  bid_increment TEXT,
  deposit_required TEXT,
  auction_terms TEXT,
  lot_number TEXT,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);
