
-- Marketplace tables migration
CREATE TABLE IF NOT EXISTS service_categories (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  journey_type TEXT NOT NULL,
  icon TEXT,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);

CREATE TABLE IF NOT EXISTS marketplace_providers (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  provider_type TEXT NOT NULL,
  business_name TEXT NOT NULL,
  category_id INTEGER REFERENCES service_categories(id),
  specializations TEXT,
  service_areas TEXT,
  contact_person TEXT,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  whatsapp TEXT,
  website TEXT,
  logo_url TEXT,
  banner_url TEXT,
  description TEXT,
  years_experience INTEGER DEFAULT 0,
  is_verified BOOLEAN DEFAULT FALSE,
  is_featured BOOLEAN DEFAULT FALSE,
  reac_certified BOOLEAN DEFAULT FALSE,
  company_registration TEXT,
  tax_clearance TEXT,
  insurance_details TEXT,
  business_address TEXT,
  operating_hours TEXT,
  service_radius INTEGER DEFAULT 0,
  rating REAL DEFAULT 0,
  review_count INTEGER DEFAULT 0,
  projects_completed INTEGER DEFAULT 0,
  response_time INTEGER DEFAULT 24,
  status TEXT DEFAULT 'active',
  availability_status TEXT DEFAULT 'available',
  minimum_project_size INTEGER,
  maximum_project_size INTEGER,
  hourly_rate INTEGER,
  daily_rate INTEGER,
  project_rate INTEGER,
  emergency_services BOOLEAN DEFAULT FALSE,
  warranty_period INTEGER,
  payment_terms TEXT,
  payment_methods TEXT,
  portfolio_images TEXT,
  certifications TEXT,
  languages_spoken TEXT,
  team_size INTEGER,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);

CREATE TABLE IF NOT EXISTS artisan_skills (
  id SERIAL PRIMARY KEY,
  provider_id INTEGER REFERENCES marketplace_providers(id),
  skill_name TEXT NOT NULL,
  proficiency_level TEXT NOT NULL,
  certification_body TEXT,
  certification_number TEXT,
  issue_date TEXT,
  expiry_date TEXT,
  document_url TEXT,
  is_verified BOOLEAN DEFAULT FALSE,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);

CREATE TABLE IF NOT EXISTS training_programs (
  id SERIAL PRIMARY KEY,
  provider_id INTEGER REFERENCES marketplace_providers(id),
  program_name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  duration_hours INTEGER,
  duration_weeks INTEGER,
  price INTEGER,
  max_participants INTEGER,
  prerequisites TEXT,
  learning_outcomes TEXT,
  course_outline TEXT,
  materials_included TEXT,
  provides_certificate BOOLEAN DEFAULT FALSE,
  certificate_type TEXT,
  accreditation_body TEXT,
  schedule_type TEXT,
  start_date TEXT,
  end_date TEXT,
  class_times TEXT,
  location TEXT,
  delivery_method TEXT,
  status TEXT DEFAULT 'active',
  enrollment_count INTEGER DEFAULT 0,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);

CREATE TABLE IF NOT EXISTS building_materials (
  id SERIAL PRIMARY KEY,
  supplier_id INTEGER REFERENCES marketplace_providers(id),
  product_name TEXT NOT NULL,
  product_description TEXT,
  category TEXT,
  subcategory TEXT,
  brand TEXT,
  model TEXT,
  specifications TEXT,
  dimensions TEXT,
  weight TEXT,
  color TEXT,
  material TEXT,
  unit_price INTEGER,
  unit_type TEXT,
  bulk_pricing TEXT,
  stock_quantity INTEGER DEFAULT 0,
  minimum_order INTEGER DEFAULT 1,
  lead_time_days INTEGER DEFAULT 0,
  product_images TEXT,
  status TEXT DEFAULT 'available',
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);

CREATE TABLE IF NOT EXISTS project_requests (
  id SERIAL PRIMARY KEY,
  client_id INTEGER REFERENCES users(id),
  property_id INTEGER REFERENCES properties(id),
  project_title TEXT NOT NULL,
  project_description TEXT,
  project_type TEXT NOT NULL,
  category_id INTEGER REFERENCES service_categories(id),
  budget_min INTEGER,
  budget_max INTEGER,
  timeline_weeks INTEGER,
  preferred_start_date TEXT,
  project_address TEXT,
  project_city TEXT,
  project_district TEXT,
  images TEXT,
  documents TEXT,
  status TEXT DEFAULT 'open',
  proposals_count INTEGER DEFAULT 0,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
  updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);
