
name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: beedab_ci
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || pnpm i
      - name: Typecheck
        run: npm run typecheck || pnpm typecheck
      - name: Lint
        run: npm run lint || pnpm lint
      - name: Test
        run: npm run test || pnpm test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/beedab_ci
      - name: Build
        run: npm run build || pnpm build
      - name: Drizzle drift (best-effort)
        run: npm run db:check || echo "db:check not configured"
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/beedab_ci
