name: client-ci
on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - "shared/**"
      - ".github/workflows/client-ci.yml"
  pull_request:
    paths:
      - "client/**"
      - "shared/**"
      - ".github/workflows/client-ci.yml"

concurrency:
  group: client-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Client typecheck
        run: npm run -w client typecheck

      - name: Client lint
        run: npm run -w client lint

      - name: Client build (non-blocking)
        run: npm run -w client build
        continue-on-error: true
