name: k6 Load Test

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  k6:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: beedab
          POSTGRES_USER: beedab
          POSTGRES_PASSWORD: beedab
        options: >-
          --health-cmd "pg_isready -d beedab -U beedab" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      # checkov:skip=CKV_SECRET_4 Ephemeral CI Postgres service credentials
      DATABASE_URL: postgresql://beedab:beedab@localhost:5432/beedab?sslmode=disable
      NODE_ENV: production
      FORCE_DB_MIGRATIONS: 'true'
      FORCE_DB_SEED: 'true'
      PORT: 5000
      PGSSLMODE: disable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Start API server
        run: |
          nohup npm run start >/tmp/server.log 2>&1 &
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:5000/api/health >/dev/null; then
              break
            fi
            sleep 2
          done
      - name: Run k6 smoke
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/load/properties-search.js
        env:
          K6_BASE_URL: http://127.0.0.1:5000
      - name: Upload server logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-server-log
          path: /tmp/server.log
          if-no-files-found: ignore
