name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    services:
      postgres:
        image: postgis/postgis:15-3.4
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: beedab
          POSTGRES_USER: beedab
          POSTGRES_PASSWORD: beedab
        options: >-
          --health-cmd "pg_isready -d beedab -U beedab" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      # checkov:skip=CKV_SECRET_4 Ephemeral CI Postgres service credentials
      DATABASE_URL: postgresql://beedab:beedab@localhost:5432/beedab?sslmode=disable
      FORCE_DB_MIGRATIONS: 'true'
      FORCE_DB_SEED: 'true'
      PORT: 5000
      PGSSLMODE: disable
      NODE_ENV: production
      JWT_SECRET: test-secret
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build web client
        run: npm run build
      - name: Start API server
        run: |
          nohup npm run start >/tmp/server.log 2>&1 &
      - name: Wait for API server health
        run: |
          scripts/wait-for-http.sh "http://127.0.0.1:${PORT:-5000}/health" 120 || {
            echo "API failed to become healthy for Lighthouse run"
            tail -n 200 /tmp/server.log || true
            exit 1
          }
      - name: Run Lighthouse CI
        run: |
          npx lhci autorun --collect.startServer=false --upload.target=temporary-public-storage
      - name: Upload server logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-server-log
          path: /tmp/server.log
          if-no-files-found: ignore
