name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: beedab
          POSTGRES_USER: beedab
          POSTGRES_PASSWORD: beedab
        options: >-
          --health-cmd "pg_isready -d beedab -U beedab" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      # checkov:skip=CKV_SECRET_4 Ephemeral CI Postgres service credentials
      DATABASE_URL: postgresql://beedab:beedab@localhost:5432/beedab
      NODE_ENV: production
      FORCE_DB_MIGRATIONS: 'true'
      FORCE_DB_SEED: 'true'
      PORT: 5000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build web client
        run: npm run build
      - name: Start API server
        run: |
          nohup npm run start >/tmp/server.log 2>&1 &
      - name: Start web preview
        run: |
          nohup npm run preview -- --port 4173 --strictPort >/tmp/preview.log 2>&1 &
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:4173/ >/dev/null; then
              break
            fi
            sleep 2
          done
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: ./lighthouserc.json
          temporaryPublicStorage: true
      - name: Upload server logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-server-log
          path: /tmp/server.log
          if-no-files-found: ignore
      - name: Upload preview logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-preview-log
          path: /tmp/preview.log
          if-no-files-found: ignore
