name: Semgrep SAST

on:
  pull_request:
  push:
    branches: [main]

jobs:
  semgrep:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: semgrep/semgrep-action@v1
        id: semgrep
        with:
          config: p/ci
          generateSarif: true
          publishToken: "${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork ? '' : secrets.SEMGREP_APP_TOKEN }}"
      - name: Upload SARIF to GitHub Security
        if: always() && steps.semgrep.outputs.sarif != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.semgrep.outputs.sarif }}
          category: semgrep
      - name: Upload SARIF artifact
        if: always() && steps.semgrep.outputs.sarif != ''
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: ${{ steps.semgrep.outputs.sarif }}
          if-no-files-found: ignore
