name: ZAP Baseline Scan

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  zap:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Start BeeDab API
        env:
          # checkov:skip=CKV_SECRET_4 Ephemeral CI Postgres service credentials
          DATABASE_URL: postgresql://beedab:beedab@localhost:5432/beedab
          NODE_ENV: production
          FORCE_DB_MIGRATIONS: 'true'
          FORCE_DB_SEED: 'true'
          PORT: 5000
        run: |
          docker run -d --name zap-postgres -e POSTGRES_DB=beedab -e POSTGRES_USER=beedab -e POSTGRES_PASSWORD=beedab -p 5432:5432 postgres:15
          until docker exec zap-postgres pg_isready -d beedab -U beedab; do sleep 2; done
          nohup npm run start >/tmp/server.log 2>&1 &
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:5000/api/health >/dev/null; then
              break
            fi
            sleep 2
          done
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://host.docker.internal:5000'
          cmd_options: '-a -j'
          allow_issue_writing: false
      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.zip
          if-no-files-found: ignore
      - name: Upload server logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-server-log
          path: /tmp/server.log
          if-no-files-found: ignore
